fix: yaml identitation error

diff --git a/.github/workflows/post_to_mastodon.yml b/.github/workflows/post_to_mastodon.yml
--- a/.github/workflows/post_to_mastodon.yml
+++ b/.github/workflows/post_to_mastodon.yml
@@ -21,11 +21,11 @@ jobs:
           timeout_minutes: 2
           max_attempts: 3
           command: |
-          curl -X POST -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
-          -F "status=New release in Snakemake project '${{ github.event.repository.full_name }}' for pull request '#${{ github.event.pull_request.number }}' merged: '${{ github.event.pull_request.title }}'. Get the latest release from #Bioconda or #Pypi." \
-          https://fediscience.org/api/v1/statuses \
-          -w "\nResponse code: %{http_code}\n" \
-          -f || {
-            echo "Failed to post to Mastodon"
-            exit 1
-          }
+                     curl -X POST -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
+                     -F "status=New release in Snakemake project '${{ github.event.repository.full_name }}' for pull request '#${{ github.event.pull_request.number }}' merged: '${{ github.event.pull_request.title }}'. Get the latest release from #Bioconda or #Pypi." \
+                     https://fediscience.org/api/v1/statuses \
+                     -w "\nResponse code: %{http_code}\n" \
+                     -f || {
+                       echo "Failed to post to Mastodon"
+                       exit 1
+                     }
